# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: S:/projects/mi400-eam-poc/source/io_constraints.xdc

# XDC: S:/projects/mi400-eam-poc/source/clock_constraints.xdc

# Block Designs: bd/PcieBridge/PcieBridge.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PcieBridge || ORIG_REF_NAME==PcieBridge} -quiet] -quiet

# IP: bd/PcieBridge/ip/PcieBridge_xdma_0_0/PcieBridge_xdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PcieBridge_xdma_0_0 || ORIG_REF_NAME==PcieBridge_xdma_0_0} -quiet] -quiet

# IP: bd/PcieBridge/ip/PcieBridge_axis_dwidth_converter_0_0/PcieBridge_axis_dwidth_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PcieBridge_axis_dwidth_converter_0_0 || ORIG_REF_NAME==PcieBridge_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: bd/PcieBridge/ip/PcieBridge_mdm_0_0/PcieBridge_mdm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PcieBridge_mdm_0_0 || ORIG_REF_NAME==PcieBridge_mdm_0_0} -quiet] -quiet

# IP: bd/PcieBridge/ip/PcieBridge_util_ds_buf_0/PcieBridge_util_ds_buf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PcieBridge_util_ds_buf_0 || ORIG_REF_NAME==PcieBridge_util_ds_buf_0} -quiet] -quiet

# XDC: s:/projects/mi400-eam-poc/proj-golden/mi400-eam-poc-golden.gen/sources_1/bd/PcieBridge/PcieBridge_ooc.xdc
