# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: S:/projects/mi400-eam-poc/proj-golden/mi400-eam-poc-golden.srcs/sources_1/bd/PcieBridge/ip/PcieBridge_auto_cc_0/PcieBridge_auto_cc_0.xci
# IP: The module: 'PcieBridge_auto_cc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: s:/projects/mi400-eam-poc/proj-golden/mi400-eam-poc-golden.gen/sources_1/bd/PcieBridge/ip/PcieBridge_auto_cc_0_1/PcieBridge_auto_cc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'PcieBridge_auto_cc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: s:/projects/mi400-eam-poc/proj-golden/mi400-eam-poc-golden.gen/sources_1/bd/PcieBridge/ip/PcieBridge_auto_cc_0_1/PcieBridge_auto_cc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PcieBridge_auto_cc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: S:/projects/mi400-eam-poc/proj-golden/mi400-eam-poc-golden.srcs/sources_1/bd/PcieBridge/ip/PcieBridge_auto_cc_0/PcieBridge_auto_cc_0.xci
# IP: The module: 'PcieBridge_auto_cc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: s:/projects/mi400-eam-poc/proj-golden/mi400-eam-poc-golden.gen/sources_1/bd/PcieBridge/ip/PcieBridge_auto_cc_0_1/PcieBridge_auto_cc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'PcieBridge_auto_cc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: s:/projects/mi400-eam-poc/proj-golden/mi400-eam-poc-golden.gen/sources_1/bd/PcieBridge/ip/PcieBridge_auto_cc_0_1/PcieBridge_auto_cc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PcieBridge_auto_cc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
