# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: S:/projects/mi400-eam-poc/source/io_constraints.xdc

# XDC: S:/projects/mi400-eam-poc/source/clock_constraints.xdc

# Block Designs: bd/PcieBridge/PcieBridge.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PcieBridge || ORIG_REF_NAME==PcieBridge} -quiet] -quiet

# IP: bd/PcieBridge/ip/PcieBridge_xdma_0_0/PcieBridge_xdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PcieBridge_xdma_0_0 || ORIG_REF_NAME==PcieBridge_xdma_0_0} -quiet] -quiet

# IP: bd/PcieBridge/ip/PcieBridge_axis_dwidth_converter_0_0/PcieBridge_axis_dwidth_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PcieBridge_axis_dwidth_converter_0_0 || ORIG_REF_NAME==PcieBridge_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: bd/PcieBridge/ip/PcieBridge_mdm_0_0/PcieBridge_mdm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PcieBridge_mdm_0_0 || ORIG_REF_NAME==PcieBridge_mdm_0_0} -quiet] -quiet

# IP: bd/PcieBridge/ip/PcieBridge_util_ds_buf_0/PcieBridge_util_ds_buf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PcieBridge_util_ds_buf_0 || ORIG_REF_NAME==PcieBridge_util_ds_buf_0} -quiet] -quiet

# Block Designs: bd/MicroBlazeCore/MicroBlazeCore.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeCore || ORIG_REF_NAME==MicroBlazeCore} -quiet] -quiet

# IP: bd/MicroBlazeCore/ip/MicroBlazeCore_microblaze_0_0/MicroBlazeCore_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeCore_microblaze_0_0 || ORIG_REF_NAME==MicroBlazeCore_microblaze_0_0} -quiet] -quiet

# IP: bd/MicroBlazeCore/ip/MicroBlazeCore_axi_timer_0_0/MicroBlazeCore_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeCore_axi_timer_0_0 || ORIG_REF_NAME==MicroBlazeCore_axi_timer_0_0} -quiet] -quiet

# IP: bd/MicroBlazeCore/ip/MicroBlazeCore_axi_timer_1_0/MicroBlazeCore_axi_timer_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeCore_axi_timer_1_0 || ORIG_REF_NAME==MicroBlazeCore_axi_timer_1_0} -quiet] -quiet

# IP: bd/MicroBlazeCore/ip/MicroBlazeCore_axi_uartlite_0_0/MicroBlazeCore_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeCore_axi_uartlite_0_0 || ORIG_REF_NAME==MicroBlazeCore_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/MicroBlazeCore/ip/MicroBlazeCore_dlmb_v10_0/MicroBlazeCore_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeCore_dlmb_v10_0 || ORIG_REF_NAME==MicroBlazeCore_dlmb_v10_0} -quiet] -quiet

# IP: bd/MicroBlazeCore/ip/MicroBlazeCore_ilmb_v10_0/MicroBlazeCore_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeCore_ilmb_v10_0 || ORIG_REF_NAME==MicroBlazeCore_ilmb_v10_0} -quiet] -quiet

# IP: bd/MicroBlazeCore/ip/MicroBlazeCore_dlmb_bram_if_cntlr_0/MicroBlazeCore_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeCore_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==MicroBlazeCore_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MicroBlazeCore/ip/MicroBlazeCore_ilmb_bram_if_cntlr_0/MicroBlazeCore_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeCore_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==MicroBlazeCore_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MicroBlazeCore/ip/MicroBlazeCore_lmb_bram_0/MicroBlazeCore_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeCore_lmb_bram_0 || ORIG_REF_NAME==MicroBlazeCore_lmb_bram_0} -quiet] -quiet

# IP: bd/MicroBlazeCore/ip/MicroBlazeCore_xbar_0/MicroBlazeCore_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeCore_xbar_0 || ORIG_REF_NAME==MicroBlazeCore_xbar_0} -quiet] -quiet

# IP: bd/MicroBlazeCore/ip/MicroBlazeCore_auto_cc_0/MicroBlazeCore_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeCore_auto_cc_0 || ORIG_REF_NAME==MicroBlazeCore_auto_cc_0} -quiet] -quiet

# IP: bd/MicroBlazeCore/ip/MicroBlazeCore_microblaze_0_axi_periph_0/MicroBlazeCore_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeCore_microblaze_0_axi_periph_0 || ORIG_REF_NAME==MicroBlazeCore_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/MicroBlazeCore/ip/MicroBlazeCore_microblaze_0_axi_intc_0/MicroBlazeCore_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeCore_microblaze_0_axi_intc_0 || ORIG_REF_NAME==MicroBlazeCore_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/MicroBlazeCore/ip/MicroBlazeCore_microblaze_0_xlconcat_0/MicroBlazeCore_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeCore_microblaze_0_xlconcat_0 || ORIG_REF_NAME==MicroBlazeCore_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/MicroBlazeCore/ip/MicroBlazeCore_rst_clk_wiz_1_100M_0/MicroBlazeCore_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeCore_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MicroBlazeCore_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/MicroBlazeCore/ip/MicroBlazeCore_Axi4FabricBridge_0_0/MicroBlazeCore_Axi4FabricBridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeCore_Axi4FabricBridge_0_0 || ORIG_REF_NAME==MicroBlazeCore_Axi4FabricBridge_0_0} -quiet] -quiet

# XDC: s:/projects/mi400-eam-poc/proj-mcu/mi400-eam-poc-mcu.gen/sources_1/bd/PcieBridge/PcieBridge_ooc.xdc

# XDC: s:/projects/mi400-eam-poc/proj-mcu/mi400-eam-poc-mcu.gen/sources_1/bd/MicroBlazeCore/MicroBlazeCore_ooc.xdc
