# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: s:/projects/mi400-eam-poc/proj-mcu/mi400-eam-poc-mcu.srcs/sources_1/bd/MicroBlazeCore/ip/MicroBlazeCore_microblaze_0_axi_intc_0/MicroBlazeCore_microblaze_0_axi_intc_0.xci
# IP: The module: 'MicroBlazeCore_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: s:/projects/mi400-eam-poc/proj-mcu/mi400-eam-poc-mcu.gen/sources_1/bd/MicroBlazeCore/ip/MicroBlazeCore_microblaze_0_axi_intc_0/MicroBlazeCore_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlazeCore_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: s:/projects/mi400-eam-poc/proj-mcu/mi400-eam-poc-mcu.gen/sources_1/bd/MicroBlazeCore/ip/MicroBlazeCore_microblaze_0_axi_intc_0/MicroBlazeCore_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlazeCore_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: s:/projects/mi400-eam-poc/proj-mcu/mi400-eam-poc-mcu.gen/sources_1/bd/MicroBlazeCore/ip/MicroBlazeCore_microblaze_0_axi_intc_0/MicroBlazeCore_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlazeCore_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: s:/projects/mi400-eam-poc/proj-mcu/mi400-eam-poc-mcu.srcs/sources_1/bd/MicroBlazeCore/ip/MicroBlazeCore_microblaze_0_axi_intc_0/MicroBlazeCore_microblaze_0_axi_intc_0.xci
# IP: The module: 'MicroBlazeCore_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: s:/projects/mi400-eam-poc/proj-mcu/mi400-eam-poc-mcu.gen/sources_1/bd/MicroBlazeCore/ip/MicroBlazeCore_microblaze_0_axi_intc_0/MicroBlazeCore_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlazeCore_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: s:/projects/mi400-eam-poc/proj-mcu/mi400-eam-poc-mcu.gen/sources_1/bd/MicroBlazeCore/ip/MicroBlazeCore_microblaze_0_axi_intc_0/MicroBlazeCore_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlazeCore_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: s:/projects/mi400-eam-poc/proj-mcu/mi400-eam-poc-mcu.gen/sources_1/bd/MicroBlazeCore/ip/MicroBlazeCore_microblaze_0_axi_intc_0/MicroBlazeCore_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlazeCore_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
