set_property SRC_FILE_INFO {cfile:S:/projects/mi400-eam-poc/source/io_constraints.xdc rfile:../../../../source/io_constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y13 [get_ports MICROBLAZE_UART_RX]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA13 [get_ports MICROBLAZE_UART_TX]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T7} [get_ports PCIE_CLOCK_P]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T24 IOSTANDARD LVDS} [get_ports FPGA_CLK_100MHZ_P]
